import type { NoteMaterialSeedEntry } from "./types"

/**
 * Curated parent materials for quiz and alias seeding.
 * Aliases are optional explicit PerfumeNotes.name matches (lowercase).
 */
export const NOTE_MATERIAL_SEED: NoteMaterialSeedEntry[] = [
  { slug: "bergamot", name: "Bergamot", family: "citrus", aliases: ["italian bergamot", "sicilian bergamot", "calabrian bergamot", "zesty bergamot"] },
  { slug: "lemon", name: "Lemon", family: "citrus" },
  { slug: "lime", name: "Lime", family: "citrus" },
  { slug: "orange", name: "Orange", family: "citrus", aliases: ["sweet orange", "mandarin orange", "blood orange"] },
  { slug: "grapefruit", name: "Grapefruit", family: "citrus" },
  { slug: "mandarin", name: "Mandarin", family: "citrus" },
  { slug: "neroli", name: "Neroli", family: "citrus", aliases: ["tunisian neroli"] },
  { slug: "petitgrain", name: "Petitgrain", family: "citrus" },
  { slug: "yuzu", name: "Yuzu", family: "citrus" },
  { slug: "mint", name: "Mint", family: "citrus" },
  { slug: "rose", name: "Rose", family: "florals", aliases: ["bulgarian rose", "turkish rose", "rose petals"] },
  { slug: "jasmine", name: "Jasmine", family: "florals", aliases: ["jasmine petals"] },
  { slug: "iris", name: "Iris", family: "florals", aliases: ["orris", "orris root", "orris butter", "iris butter"] },
  { slug: "violet", name: "Violet", family: "florals", aliases: ["violet leaf"] },
  { slug: "peony", name: "Peony", family: "florals" },
  { slug: "lily", name: "Lily", family: "florals", aliases: ["lily of the valley", "casablanca lily"] },
  { slug: "geranium", name: "Geranium", family: "florals" },
  { slug: "tuberose", name: "Tuberose", family: "florals" },
  { slug: "ylang ylang", name: "Ylang Ylang", family: "florals" },
  { slug: "magnolia", name: "Magnolia", family: "florals" },
  { slug: "orange blossom", name: "Orange Blossom", family: "florals" },
  { slug: "osmanthus", name: "Osmanthus", family: "florals" },
  { slug: "mimosa", name: "Mimosa", family: "florals" },
  { slug: "sandalwood", name: "Sandalwood", family: "woods", aliases: ["australian sandalwood", "mysore sandalwood", "sandal"] },
  { slug: "cedar", name: "Cedar", family: "woods", aliases: ["cedarwood", "cedarwood shavings"] },
  { slug: "vetiver", name: "Vetiver", family: "woods", aliases: ["smoked vetiver", "madagascar vetiver"] },
  { slug: "oud", name: "Oud", family: "woods", aliases: ["agarwood", "oudh"] },
  { slug: "pine", name: "Pine", family: "woods" },
  { slug: "cypress", name: "Cypress", family: "woods" },
  { slug: "amber", name: "Amber", family: "orientals", aliases: ["indian amber", "golden amber", "honeyed amber", "salted amber", "balsamic amber", "amber warmth"] },
  { slug: "patchouli", name: "Patchouli", family: "orientals", aliases: ["east indian patchouli", "indonesian patchouli", "aged patchouli", "patchouli resin", "golden patchouli"] },
  { slug: "vanilla", name: "Vanilla", family: "gourmands", aliases: ["madagascar vanilla", "bourbon vanilla", "tahitian vanilla", "vanilla absolute", "madagascar vanilla bean"] },
  { slug: "tonka bean", name: "Tonka Bean", family: "gourmands", aliases: ["tonka", "tonka absolute", "brazilian tonka bean absolute"] },
  { slug: "honey", name: "Honey", family: "gourmands" },
  { slug: "caramel", name: "Caramel", family: "gourmands" },
  { slug: "chocolate", name: "Chocolate", family: "gourmands", aliases: ["cocoa"] },
  { slug: "coffee", name: "Coffee", family: "gourmands" },
  { slug: "almond", name: "Almond", family: "gourmands", aliases: ["almond blossom", "candied almond", "creamy almond"] },
  { slug: "marshmallow", name: "Marshmallow", family: "gourmands", aliases: ["marshmallow fluff", "whipped marshmallow"] },
  { slug: "musk", name: "Musk", family: "orientals", aliases: ["soft musk", "skin musk", "solar musk", "natural musk"] },
  { slug: "incense", name: "Incense", family: "orientals", aliases: ["frankincense", "oman frankincense", "soft incense", "incense smoke"] },
  { slug: "myrrh", name: "Myrrh", family: "orientals" },
  { slug: "benzoin", name: "Benzoin", family: "orientals", aliases: ["benzoin resinoid"] },
  { slug: "labdanum", name: "Labdanum", family: "orientals", aliases: ["labdanum resin from spain"] },
  { slug: "tobacco", name: "Tobacco", family: "orientals" },
  { slug: "leather", name: "Leather", family: "orientals" },
  { slug: "saffron", name: "Saffron", family: "orientals" },
  { slug: "cinnamon", name: "Cinnamon", family: "orientals" },
  { slug: "cardamom", name: "Cardamom", family: "orientals" },
  { slug: "clove", name: "Clove", family: "orientals" },
  { slug: "pepper", name: "Pepper", family: "orientals", aliases: ["pink pepper", "black pepper", "crushed pink pepper"] },
  { slug: "aquatic", name: "Aquatic", family: "aquatics", aliases: ["ozonic", "marine", "sea salt", "sea breeze"] },
  { slug: "apple", name: "Apple", family: "florals", aliases: ["green apple", "red apple", "granny smith apple"] },
  { slug: "peach", name: "Peach", family: "florals", aliases: ["peach nectar"] },
  { slug: "pear", name: "Pear", family: "florals" },
  { slug: "raspberry", name: "Raspberry", family: "florals", aliases: ["wild strawberry"] },
  { slug: "fig", name: "Fig", family: "florals", aliases: ["fig milk"] },
  { slug: "lavender", name: "Lavender", family: "florals", aliases: ["lavender mist"] },
  { slug: "tea", name: "Tea", family: "florals", aliases: ["black tea", "green tea", "steaming black tea"] },
  { slug: "ambergris", name: "Ambergris", family: "orientals" },
  { slug: "oakmoss", name: "Oakmoss", family: "woods", aliases: ["oak moss", "tree moss"] },
]
