/**
 * Translation keys for validation messages. When displaying field errors from
 * form schemas, pass the error through your locale's t() so messages are localized, e.g.:
 *   error={getTranslatedError(field?.errors, t)}
 */
export const validationKeys = {
  emailInvalid: "validation.emailInvalid",
  urlInvalid: "validation.urlInvalid",
  websiteRequired: "validation.websiteRequired",
  websiteRequiredShort: "validation.websiteRequiredShort",
  phoneInvalid: "validation.phoneInvalid",
  yearInvalid: "validation.yearInvalid",
  passwordMinLength: "validation.passwordMinLength",
  passwordMaxLength: "validation.passwordMaxLength",
  passwordLowercase: "validation.passwordLowercase",
  passwordUppercase: "validation.passwordUppercase",
  passwordNumber: "validation.passwordNumber",
  passwordSpecial: "validation.passwordSpecial",
  passwordNoSpaces: "validation.passwordNoSpaces",
  ratingMin: "validation.ratingMin",
  ratingMax: "validation.ratingMax",
  amountFormat: "validation.amountFormat",
  priceFormat: "validation.priceFormat",
  nameRequired: "validation.nameRequired",
  nameMin: "validation.nameMin",
  nameMax: "validation.nameMax",
  descriptionRequired: "validation.descriptionRequired",
  descriptionMin: "validation.descriptionMin",
  descriptionMax: "validation.descriptionMax",
  countryMin: "validation.countryMin",
  countryMax: "validation.countryMax",
  addressMin: "validation.addressMin",
  addressMax: "validation.addressMax",
  perfumeHouseRequired: "validation.perfumeHouseRequired",
  perfumeIdRequired: "validation.perfumeIdRequired",
  placeOfPurchaseMax: "validation.placeOfPurchaseMax",
  tradePreference: "validation.tradePreference",
  perfumeTypeRequired: "validation.perfumeTypeRequired",
  atLeastOneRating: "validation.atLeastOneRating",
  ratingIdRequired: "validation.ratingIdRequired",
  userPerfumeIdRequired: "validation.userPerfumeIdRequired",
  commentRequired: "validation.commentRequired",
  commentMax: "validation.commentMax",
  commentIdRequired: "validation.commentIdRequired",
  wishlistAction: "validation.wishlistAction",
  confirmPasswordRequired: "validation.confirmPasswordRequired",
  firstNameRequired: "validation.firstNameRequired",
  firstNameMax: "validation.firstNameMax",
  lastNameRequired: "validation.lastNameRequired",
  lastNameMax: "validation.lastNameMax",
  usernameMin: "validation.usernameMin",
  usernameMax: "validation.usernameMax",
  usernameFormat: "validation.usernameFormat",
  acceptTerms: "validation.acceptTerms",
  passwordsDoNotMatch: "validation.passwordsDoNotMatch",
  passwordRequired: "validation.passwordRequired",
  currentPasswordRequired: "validation.currentPasswordRequired",
  confirmNewPasswordRequired: "validation.confirmNewPasswordRequired",
  newPasswordsDoNotMatch: "validation.newPasswordsDoNotMatch",
  newPasswordDifferent: "validation.newPasswordDifferent",
  resetTokenRequired: "validation.resetTokenRequired",
  searchQueryMax: "validation.searchQueryMax",
  houseNameMax: "validation.houseNameMax",
  priceMinZero: "validation.priceMinZero",
  priceMaxZero: "validation.priceMaxZero",
  ratingRangeMin: "validation.ratingRangeMin",
  ratingRangeMax: "validation.ratingRangeMax",
  roleInvalid: "validation.roleInvalid",
  timeframeInvalid: "validation.timeframeInvalid",
  exportFormatInvalid: "validation.exportFormatInvalid",
  recipientIdRequired: "validation.recipientIdRequired",
  subjectMax: "validation.subjectMax",
  messageMin: "validation.messageMin",
  messageMax: "validation.messageMax",
} as const

/** Pass validation error (or undefined) and next-intl t(); returns translated message or undefined. */
export const getTranslatedError = (
  error: string | string[] | undefined,
  t: (key: string) => string
): string | undefined => {
  const msg = Array.isArray(error) ? error[0] : error
  return msg ? t(msg) : undefined
}
